name: Lint and Push

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # Install your project dependencies if needed
          # pip install -r requirements.txt

      - name: Run flake8 linting
        run: |
          # Run full flake8 check and display all errors
          flake8 . --count --show-source --statistics --max-complexity=10 --max-line-length=127 --tee --output-file=flake8-report.txt

      - name: Display flake8 results
        if: always()
        run: |
          echo "=== FLAKE8 LINTING RESULTS ==="
          if [ -f flake8-report.txt ]; then
            cat flake8-report.txt
          fi
          echo "================================"

      - name: Configure Git
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push if linting passed
        if: success()
        run: |
          # Check if there are any changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Auto-commit: flake8 linting passed"
            git push
          else
            echo "No changes to commit"
          fi
